# Building workflow for ubuntu 20.04 or later.
#
# 1. Use this docker file to build the executable.
#    docker build -t texconv -f Dockerfile_Ubuntu ./
#
# 2. Run the built image. 
#    docker run texconv
#
# 3. Use "docker cp" to get the built executables.
#    docker cp <CONTAINER ID>:/Texconv-Custom-DLL/texconv ./
#    docker cp <CONTAINER ID>:/Texconv-Custom-DLL/texassemble ./
#
# 4. Also, you can get the built shared library.
#    docker cp <CONTAINER ID>:/Texconv-Custom-DLL/libtexconv.so ./
#
# Notes:
#   -You can add JPEG and PNG support with build-arg
#    docker build --build-arg JPGPNG=true -t texconv -f Dockerfile_Ubuntu ./

# Base image
FROM matyalatte/ubuntu20.04-cmake3.25:latest

# Add JPEG and PNG support when true
ARG JPGPNG=false

# Install packages
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        wget ca-certificates build-essential git cmake && \
    if [ "$JPGPNG" = "true" ]; then \
        apt-get install -y --no-install-recommends libjpeg-dev libpng-dev; \
    fi && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Clone repo
COPY . /Texconv-Custom-DLL
WORKDIR /Texconv-Custom-DLL
RUN git submodule update --init --recursive --recommend-shallow --depth 1

# Build
WORKDIR /Texconv-Custom-DLL/shell_scripts
RUN if [ "$JPGPNG" = "true" ]; then \
        bash build_with_jpg_png.sh && \
        bash build_as_exe_with_jpg_png.sh; \
    else \
        bash build.sh && \
        bash build_as_exe.sh; \
    fi
